import {
  AlertTriangle,
  ArchiveRestore,
  BarChart3,
  BadgeAlert,
  Calculator,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  Clock3,
  Coins,
  CreditCard,
  FileText,
  Gauge,
  HelpCircle,
  LayoutDashboard,
  ListFilter,
  LogOut,
  Menu,
  MoreVertical,
  Package,
  PackageCheck,
  PackagePlus,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  Power,
  RotateCcw,
  Search,
  Settings,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Trash2,
  Undo2,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  X,
} from "lucide-react";

const icons = {
  dashboard: LayoutDashboard,
  wallet: Wallet,
  pos: ShoppingCart,
  users: Users,
  coins: Coins,
  box: Package,
  receipt: FileText,
  debt: Clock3,
  history: Clock3,
  chart: BarChart3,
  check: CheckCircle2,
  clipboard: ClipboardCheck,
  trend: TrendingUp,
  calculator: Calculator,
  help: HelpCircle,
  logout: LogOut,
  search: Search,
  settings: Settings,
  spark: Sparkles,
  alert: AlertTriangle,
  "archive-restore": ArchiveRestore,
  "badge-alert": BadgeAlert,
  gauge: Gauge,
  filter: ListFilter,
  "more-vertical": MoreVertical,
  "package-check": PackageCheck,
  "package-plus": PackagePlus,
  edit: Pencil,
  power: Power,
  reset: RotateCcw,
  sliders: SlidersHorizontal,
  trash: Trash2,
  return: Undo2,
  "arrow-left-to-line": Undo2,
  truck: Truck,
  chevron: ChevronRight,
  credit: CreditCard,
  x: X,
  menu: Menu,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  plus: Plus,
  back: ChevronLeft,
};

export default function AppIcon({ name, className = "h-4 w-4" }) {
  const Icon = icons[name] || Sparkles;
  return <Icon className={className} strokeWidth={1.8} aria-hidden="true" />;
}
