export const providerLogoRules = [
  { keywords: ["telkomsel"], mark: "Tsel", label: "Telkomsel", background: "#e11d48", color: "#ffffff", asset: "telkomsel.png" },
  { keywords: ["indosat", "im3"], mark: "IM3", label: "Indosat", background: "#facc15", color: "#111827", asset: "indosat.png" },
  { keywords: ["axis"], mark: "AX", label: "Axis", background: "#7e22ce", color: "#ffffff", asset: "axis.png" },
  { keywords: ["by u", "by.u", "byu"], mark: "by.U", label: "by.U", background: "#06b6d4", color: "#ffffff", asset: "byu.png" },
  { keywords: ["three", "tri"], mark: "3", label: "Tri", background: "#111827", color: "#ffffff", asset: "tri.png" },
  { keywords: ["smartfren", "smart"], mark: "SF", label: "Smartfren", background: "#dc2626", color: "#ffffff", asset: "smartfren.png" },
  { keywords: ["xl"], mark: "XL", label: "XL", background: "#0f766e", color: "#ffffff", asset: "xl.png" },
  { keywords: ["tagihan pln", "token pln", "token", "pln"], mark: "PLN", label: "PLN", background: "#facc15", color: "#0f172a", asset: "pln.svg" },
  { keywords: ["free fire"], mark: "FF", label: "Free Fire", background: "#f97316", color: "#ffffff", asset: "freefire.png" },
  { keywords: ["mobile legend", "mobile legends"], mark: "ML", label: "Mobile Legends", background: "#1d4ed8", color: "#ffffff", asset: "mobilelegends.jpg" },
  { keywords: ["pubg"], mark: "PUBG", label: "PUBG", background: "#f59e0b", color: "#111827", asset: "pubg.svg" },
  { keywords: ["genshin"], mark: "GI", label: "Genshin", background: "#475569", color: "#ffffff", asset: "genshin.jpg" },
  { keywords: ["honor of king", "honor of kings"], mark: "HoK", label: "Honor of Kings", background: "#7c2d12", color: "#ffffff", asset: "honorofkings.png" },
  { keywords: ["garena undawn"], mark: "UN", label: "Garena Undawn", background: "#991b1b", color: "#ffffff", asset: "undawn.png" },
  { keywords: ["garena"], mark: "G", label: "Garena", background: "#dc2626", color: "#ffffff", asset: "garena.png" },
  { keywords: ["magic chess"], mark: "MC", label: "Magic Chess", background: "#7c3aed", color: "#ffffff", asset: "magicchess.png" },
  { keywords: ["call of duty"], mark: "COD", label: "Call of Duty", background: "#111827", color: "#ffffff", asset: "callofduty.png" },
  { keywords: ["fc mobile"], mark: "FC", label: "FC Mobile", background: "#16a34a", color: "#ffffff", asset: "fcmobile.png" },
  { keywords: ["point blank"], mark: "PB", label: "Point Blank", background: "#991b1b", color: "#ffffff", asset: "pointblank.png" },
  { keywords: ["hago"], mark: "H", label: "Hago", background: "#f59e0b", color: "#111827", asset: "hago.png" },
  { keywords: ["auz mobile"], mark: "AUZ", label: "AUZ Mobile", background: "#1f2937", color: "#ffffff", asset: "auz.jpg" },
  { keywords: ["ragnarok", "big cst"], mark: "RO", label: "Ragnarok", background: "#a855f7", color: "#ffffff", asset: "ragnarok.png" },
  { keywords: ["bpjs"], mark: "BPJS", label: "BPJS", background: "#16a34a", color: "#ffffff", asset: "bpjs.png" },
  { keywords: ["indihome", "telkom/indihome"], mark: "IH", label: "IndiHome", background: "#dc2626", color: "#ffffff", asset: "indihome.png" },
  { keywords: ["tv pasca", "tv pascabayar"], mark: "TV", label: "TV Pascabayar", background: "#1e293b", color: "#ffffff", asset: "tvpascabayar.svg" },
  { keywords: ["multifinance"], mark: "MF", label: "Multifinance", background: "#92400e", color: "#ffffff", asset: "multifinance.svg" },
  { keywords: ["e wallet", "e-wallet"], mark: "EW", label: "E-Wallet", background: "#2563eb", color: "#ffffff", asset: "ewallet.svg" },
  { keywords: ["pasar kuota", "pasar_kuota", "pasarkuota"], mark: "PK", label: "Pasar Kuota", background: "#0f766e", color: "#ffffff", asset: "pasarkuota.png" },
  { keywords: ["dana"], mark: "DANA", label: "DANA", background: "#108ee9", color: "#ffffff", asset: "dana.png" },
  { keywords: ["ovo"], mark: "OVO", label: "OVO", background: "#4c1d95", color: "#ffffff", asset: "ovo.png" },
  { keywords: ["gopay", "go pay"], mark: "Go", label: "GoPay", background: "#00a6d6", color: "#ffffff", asset: "gopay.svg" },
  { keywords: ["shopee food", "shopee pay", "shopeepay", "shopee"], mark: "S", label: "ShopeePay", background: "#ee4d2d", color: "#ffffff", asset: "shopee.svg" },
  { keywords: ["grab"], mark: "Grab", label: "Grab", background: "#00b14f", color: "#ffffff", asset: "grab.svg" },
  { keywords: ["linkaja", "link aja"], mark: "LA", label: "LinkAja", background: "#dc2626", color: "#ffffff", asset: "linkaja.svg" },
  { keywords: ["isaku"], mark: "iS", label: "iSaku", background: "#ef4444", color: "#ffffff", asset: "isaku.jpg" },
  { keywords: ["maxim"], mark: "M", label: "Maxim", background: "#facc15", color: "#111827", asset: "maxim.png" },
  { keywords: ["in driver", "indriver"], mark: "in", label: "inDrive", background: "#22c55e", color: "#0f172a", asset: "indriver.png" },
  { keywords: ["e-toll e-money", "e-money", "emoney", "e money"], mark: "eM", label: "eMoney", background: "#0f766e", color: "#ffffff", asset: "emoney.png" },
  { keywords: ["brizzi"], mark: "BRI", label: "BRIZZI", background: "#00529b", color: "#ffffff", asset: "brizzi.png" },
  { keywords: ["tapcash"], mark: "BNI", label: "TapCash", background: "#f97316", color: "#ffffff", asset: "tapcash.png" },
  { keywords: ["wahana"], mark: "WH", label: "Wahana", background: "#0f766e", color: "#ffffff", asset: "wahana.png" },
  { keywords: ["cimb", "niaga"], mark: "CIMB", label: "CIMB Niaga", background: "#b91c1c", color: "#ffffff", asset: "cimb.ico" },
  { keywords: ["danamon"], mark: "DNM", label: "Danamon", background: "#f97316", color: "#ffffff", asset: "danamon.ico" },
  { keywords: ["permata"], mark: "PB", label: "Permata Bank", background: "#0ea5e9", color: "#ffffff", asset: "permata.png" },
  { keywords: ["btn"], mark: "BTN", label: "BTN", background: "#0f4c81", color: "#ffffff", asset: "btn.png" },
  { keywords: ["jago"], mark: "Jago", label: "Bank Jago", background: "#facc15", color: "#111827", asset: "jago.png" },
  { keywords: ["jenius", "btpn"], mark: "J", label: "Jenius", background: "#06b6d4", color: "#ffffff", asset: "jenius.png" },
  { keywords: ["blu"], mark: "blu", label: "Blu BCA Digital", background: "#2563eb", color: "#ffffff", asset: "blu.png" },
  { keywords: ["seabank"], mark: "Sea", label: "SeaBank", background: "#f97316", color: "#ffffff", asset: "seabank.png" },
  { keywords: ["neo bank", "neo commerce", "bank neo"], mark: "Neo", label: "Neo Bank", background: "#f59e0b", color: "#111827", asset: "neobank.png" },
  { keywords: ["line bank"], mark: "LINE", label: "Line Bank", background: "#06c755", color: "#ffffff", asset: "linebank.png" },
  { keywords: ["motionbanking", "motion bank", "mnc bank"], mark: "MNC", label: "MotionBanking", background: "#2563eb", color: "#ffffff", asset: "motionbank.jpg" },
  { keywords: ["bsi", "syariah indonesia"], mark: "BSI", label: "BSI", background: "#0f766e", color: "#ffffff", asset: "bsi.png" },
  { keywords: ["muamalat"], mark: "BMI", label: "Bank Muamalat", background: "#7c3aed", color: "#ffffff", asset: "muamalat.ico" },
  { keywords: ["bank mega"], mark: "Mega", label: "Bank Mega", background: "#dc2626", color: "#ffffff", asset: "mega.png" },
  { keywords: ["ocbc"], mark: "OCBC", label: "OCBC NISP", background: "#dc2626", color: "#ffffff", asset: "ocbc.png" },
  { keywords: ["hsbc"], mark: "HSBC", label: "HSBC", background: "#dc2626", color: "#ffffff", asset: "hsbc.png" },
  { keywords: ["maybank"], mark: "MY", label: "Maybank", background: "#facc15", color: "#111827", asset: "maybank.png" },
  { keywords: ["panin"], mark: "Panin", label: "Panin Bank", background: "#1d4ed8", color: "#ffffff", asset: "panin.png" },
  { keywords: ["sinarmas"], mark: "SM", label: "Bank Sinarmas", background: "#dc2626", color: "#ffffff", asset: "sinarmas.png" },
  { keywords: ["bank mas", "bankmas"], mark: "BM", label: "Bank Mas", background: "#d4af37", color: "#111827", asset: "bankmas.png" },
  { keywords: ["bca"], mark: "BCA", label: "BCA", background: "#1d4ed8", color: "#ffffff", asset: "bca.png" },
  { keywords: ["mandiri"], mark: "MDR", label: "Mandiri", background: "#facc15", color: "#0f172a", asset: "mandiri.png" },
  { keywords: ["bri"], mark: "BRI", label: "BRI", background: "#00529b", color: "#ffffff", asset: "bri.png" },
  { keywords: ["bni"], mark: "BNI", label: "BNI", background: "#f97316", color: "#ffffff", asset: "bni.png" },
  { keywords: ["qris"], mark: "QR", label: "QRIS", background: "#111827", color: "#ffffff", asset: "qris.png" },
  { keywords: ["cash"], mark: "Rp", label: "Cash", background: "#16a34a", color: "#ffffff", asset: "cash.svg" },
];
