export const providerLogoWordmarks = {
  Indosat: "IM3",
  Tri: "Tri",
  "Free Fire": "FREE FIRE",
  "Mobile Legends": "MLBB",
  Genshin: "Genshin",
  "Honor of Kings": "HOK",
  "Garena Undawn": "UNDAWN",
  "Magic Chess": "Magic",
  "Call of Duty": "COD",
  "FC Mobile": "FC",
  "Point Blank": "PB",
  "AUZ Mobile": "AUZ",
  Ragnarok: "RO",
  DANA: "DANA",
  OVO: "OVO",
  ShopeePay: "Shopee",
  iSaku: "i.Saku",
  Maxim: "Maxim",
  eMoney: "e-money",
  BRIZZI: "BRIZZI",
  TapCash: "TapCash",
  Wahana: "Wahana",
  "CIMB Niaga": "CIMB",
  Danamon: "Danamon",
  "Permata Bank": "Permata",
  BTN: "BTN",
  "Bank Jago": "Jago",
  Jenius: "Jenius",
  "Blu BCA Digital": "blu",
  SeaBank: "SeaBank",
  "Neo Bank": "Neo",
  "Line Bank": "LINE",
  MotionBanking: "Motion",
  BSI: "BSI",
  "Bank Muamalat": "Muamalat",
  "Bank Mega": "Mega",
  "OCBC NISP": "OCBC",
  HSBC: "HSBC",
  Maybank: "Maybank",
  "Panin Bank": "Panin",
  "Bank Sinarmas": "Sinarmas",
  "Bank Mas": "Bank Mas",
  BCA: "BCA",
  Mandiri: "Mandiri",
  BRI: "BRI",
  BNI: "BNI",
  QRIS: "QRIS",
};
